### ISSUE TITLE
Drawing clears when canvas is resized

### ISSUE THREAD

**Issue by Bobbyperson** [BigGecko01/benperlahair#2]
When drawing, if a user resizes the window, the drawing will instantly clear. This happens after clicking "done" as well. Resizing the canvas will also change the smile back to a frown.
Steps to reproduce:
1. Draw something
2. Resize your window
3. Observe results

**Comment by decompi** [comment]
Hi, I would like to work on this issue.

**Comment by Bobbyperson** [comment]
LGTM, make a PR and let other contributors look at it please

**Comment by decompi** [comment]
Hi ,I've fixed the issue where the canvas drawing would clear and the image would revert when resizing or clicking "done" without clearing the canvas.

**Comment by Bobbyperson** [comment]
Changes fixed the drawing disappearing on canvas resize, but broke the image changing into a smile

**Comment by Bobbyperson** [comment]
When I tested on prod, my browser was still using cached sources, my mistake.
