### ISSUE TITLE
Smile only happens after clicking "clear" once.

### ISSUE THREAD

**Issue by Bobbyperson** [BigGecko01/benperlahair#6]
1. Click clear
2. Draw
3. Click done
4. Observe Smile
5. Refresh page
6. Draw
7. Click done
8. No smile

**Comment by over-loadcode** [comment]
im doing it tomorrow

**Comment by Bobbyperson** [comment]
oooooh sorry buddy the scrum master wants you to do it tonight

**Comment by over-loadcode** [comment]
i hate [Bobbyperson](https://github.com/Bobbyperson)
